from PIL import Image
from numpy import asarray

fname = "../esp32-app/src/protectli_logo.h"
image_name = "logo_little_2.png"

image = Image.open(image_name)
data = asarray(image.convert("1"))
image2 = Image.fromarray(data)

f = open(fname, "w")

f.write("// This file is automatically generated by: ../../sw/img.py\n")
f.write("#include <zephyr/drivers/display.h>\n")
f.write("#include <zephyr/display/cfb.h>\n")
f.write("void draw_logo(const struct device *dev) {\n")
f.write("\tstruct cfb_position pos;\n")

for y_idx, y in enumerate(data):
	for x_idx, x in enumerate(y):
		if x == True:
			f.write(f"\tpos.x = {x_idx};\n")
			f.write(f"\tpos.y = {y_idx};\n")
			f.write(f"\tcfb_draw_point(dev, &pos);\n");

f.write("}")
