#include <zephyr/drivers/display.h>
#include <zephyr/display/cfb.h>

void draw_logo(const struct device *dev) {
	struct cfb_position pos;
	pos.x = 58;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 1;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 2;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 3;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 4;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 5;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 6;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 7;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 8;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 9;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 10;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 11;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 12;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 13;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 14;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 15;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 16;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 17;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 18;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 19;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 20;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 21;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 22;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 23;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 24;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 25;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 26;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 27;
	cfb_draw_point(dev, &pos);
	pos.x = 39;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 93;
	pos.y = 28;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 29;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 30;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 31;
	cfb_draw_point(dev, &pos);
	pos.x = 40;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 32;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 92;
	pos.y = 33;
	cfb_draw_point(dev, &pos);
	pos.x = 41;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 91;
	pos.y = 34;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 35;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 36;
	cfb_draw_point(dev, &pos);
	pos.x = 42;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 90;
	pos.y = 37;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 38;
	cfb_draw_point(dev, &pos);
	pos.x = 43;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 39;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 89;
	pos.y = 40;
	cfb_draw_point(dev, &pos);
	pos.x = 44;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 88;
	pos.y = 41;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 42;
	cfb_draw_point(dev, &pos);
	pos.x = 45;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 87;
	pos.y = 43;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 44;
	cfb_draw_point(dev, &pos);
	pos.x = 46;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 86;
	pos.y = 45;
	cfb_draw_point(dev, &pos);
	pos.x = 47;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 85;
	pos.y = 46;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 47;
	cfb_draw_point(dev, &pos);
	pos.x = 48;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 49;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 84;
	pos.y = 48;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 83;
	pos.y = 49;
	cfb_draw_point(dev, &pos);
	pos.x = 50;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 82;
	pos.y = 50;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 51;
	cfb_draw_point(dev, &pos);
	pos.x = 51;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 52;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 81;
	pos.y = 52;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 79;
	pos.y = 53;
	cfb_draw_point(dev, &pos);
	pos.x = 53;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 54;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 80;
	pos.y = 54;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 77;
	pos.y = 55;
	cfb_draw_point(dev, &pos);
	pos.x = 55;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 56;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 76;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 78;
	pos.y = 56;
	cfb_draw_point(dev, &pos);
	pos.x = 57;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 75;
	pos.y = 57;
	cfb_draw_point(dev, &pos);
	pos.x = 58;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 74;
	pos.y = 58;
	cfb_draw_point(dev, &pos);
	pos.x = 59;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 60;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 72;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 73;
	pos.y = 59;
	cfb_draw_point(dev, &pos);
	pos.x = 61;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 70;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 60;
	cfb_draw_point(dev, &pos);
	pos.x = 62;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 63;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 71;
	pos.y = 61;
	cfb_draw_point(dev, &pos);
	pos.x = 64;
	pos.y = 62;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 62;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 62;
	cfb_draw_point(dev, &pos);
	pos.x = 67;
	pos.y = 62;
	cfb_draw_point(dev, &pos);
	pos.x = 68;
	pos.y = 62;
	cfb_draw_point(dev, &pos);
	pos.x = 69;
	pos.y = 62;
	cfb_draw_point(dev, &pos);
	pos.x = 65;
	pos.y = 63;
	cfb_draw_point(dev, &pos);
	pos.x = 66;
	pos.y = 63;
	cfb_draw_point(dev, &pos);
}
